# Generated by Django 5.2.3 on 2025-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('Programming', 'Programming'), ('SQL', 'SQL')], default='Programming', help_text='The domain of the question (e.g., Programming, SQL).', max_length=50),
        ),
    ]
